plugins {
    id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}"
}
base { archivesName = "omenwake-fabric" }
sourceSets.main.java.srcDir '../common/src/main/java'
sourceSets.main.resources.srcDir '../common/src/main/resources'
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}
